Imports System.Data.SqlClient
Module variables

    Public Sub add_lists()
        carjk2form.defects_list.Add(Defect1)
        carjk2form.defects_list.Add(Defect2)
        carjk2form.defects_list.Add(Defect3)
        carjk2form.defects_list.Add(Defect4)
        carjk2form.defects_list.Add(defect5)
        carjk2form.defects_list.Add(defect6)
        carjk2form.defects_list.Add(defect7)
        carjk2form.defects_list.Add(defect8)
        carjk2form.defects_list.Add(defect9)
        carjk2form.defects_list.Add(defect10)
        carjk2form.defects_list.Add(defect11)
        carjk2form.defects_list.Add(defect12)
        carjk2form.defects_list.Add(defect13)
        carjk2form.defects_list.Add(defect14)
        carjk2form.defects_list.Add(defect15)
        carjk2form.defects_list.Add(defect16)
        carjk2form.defects_list.Add(defect17)
        carjk2form.defects_list.Add(defect18)
        carjk2form.defects_list.Add(defect19)
        carjk2form.defects_list.Add(defect20)
        carjk2form.defects_list.Add(defect21)
        carjk2form.defects_list.Add(defect22)
        carjk2form.defects_list.Add(defect23)
        carjk2form.defects_list.Add(defect24)
        carjk2form.defects_list.Add(defect25)
        carjk2form.defects_list.Add(defect26)
        carjk2form.defects_list.Add(defect27)
        carjk2form.defects_list.Add(defect28)
        carjk2form.defects_list.Add(defect29)
        carjk2form.defects_list.Add(defect30)
        carjk2form.defects_list.Add(defect31)
        carjk2form.defects_list.Add(defect32)
        carjk2form.defects_list.Add(defect33)
        carjk2form.defects_list.Add(defect34)
        carjk2form.defects_list.Add(defect35)
        carjk2form.defects_list.Add(defect36)
    End Sub



    Public Defect1 As New List(Of Rectangle)
    Public Defect2 As New List(Of Rectangle)
    Public Defect3 As New List(Of Rectangle)
    Public Defect4 As New List(Of Rectangle)
    Public defect5 As New List(Of Rectangle)
    Public defect6 As New List(Of Rectangle)
    Public defect7 As New List(Of Rectangle)
    Public defect8 As New List(Of Rectangle)
    Public defect9 As New List(Of Rectangle)
    Public defect10 As New List(Of Rectangle)
    Public defect11 As New List(Of Rectangle)
    Public defect12 As New List(Of Rectangle)
    Public defect13 As New List(Of Rectangle)
    Public defect14 As New List(Of Rectangle)
    Public defect15 As New List(Of Rectangle)
    Public defect16 As New List(Of Rectangle)
    Public defect17 As New List(Of Rectangle)
    Public defect18 As New List(Of Rectangle)
    Public defect19 As New List(Of Rectangle)
    Public defect20 As New List(Of Rectangle)
    Public defect21 As New List(Of Rectangle)
    Public defect22 As New List(Of Rectangle)
    Public defect23 As New List(Of Rectangle)
    Public defect24 As New List(Of Rectangle)
    Public defect25 As New List(Of Rectangle)
    Public defect26 As New List(Of Rectangle)
    Public defect27 As New List(Of Rectangle)
    Public defect28 As New List(Of Rectangle)
    Public defect29 As New List(Of Rectangle)
    Public defect30 As New List(Of Rectangle)
    Public defect31 As New List(Of Rectangle)
    Public defect32 As New List(Of Rectangle)
    Public defect33 As New List(Of Rectangle)
    Public defect34 As New List(Of Rectangle)
    Public defect35 As New List(Of Rectangle)
    Public defect36 As New List(Of Rectangle)


    Public connection As New SqlConnection()

    'resets all the defect counters to zero
    Public Sub reset()
        Defect1.Clear()
        Defect2.Clear()
        Defect3.Clear()
        Defect4.Clear()
        defect5.Clear()
        defect6.Clear()
        defect7.Clear()
        defect8.Clear()
        defect9.Clear()
        defect10.Clear()
        defect11.Clear()
        defect12.Clear()
        defect13.Clear()
        defect14.Clear()
        defect15.Clear()
        defect16.Clear()
        defect17.Clear()
        defect18.Clear()
        defect19.Clear()
        defect20.Clear()
        defect21.Clear()
        defect22.Clear()
        defect23.Clear()
        defect24.Clear()
        defect25.Clear()
        defect26.Clear()
        defect27.Clear()
        defect28.Clear()
        defect29.Clear()
        defect30.Clear()
        defect31.Clear()
        defect32.Clear()
        defect33.Clear()
        defect34.Clear()
        defect35.Clear()
        defect36.Clear()
        carjk2form.defects_list.Clear()
    End Sub

    Public Sub initdb()
        If connection.State = ConnectionState.Closed Then
            Try
                connection.ConnectionString = "Data Source=desktop-sp7sh6k\sqlexpress;Initial Catalog=Defects;Integrated Security=True"
                connection.Open()
            Catch ex As Exception
                MessageBox.Show("Could not connect to database: " & ex.Message)
            End Try
        End If
    End Sub

    Public Sub closedb()
        connection.Close()
        connection.Dispose()
    End Sub
End Module
